POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title" : "List of boring blogs",
    "author ": "Jason Doez",
    "url" : "https://www.veryamazingblog.com",
    "likes" : 1
}